//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cheque()
        {
            this.ChequeTabParts = new HashSet<ChequeTabPart>();
        }
    
        public int ChequeID { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public string VerifingCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeTabPart> ChequeTabParts { get; set; }
    }
}
