//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAuthorizationData
    {
        public int ClientID { get; set; }
        public string ClientLogin { get; set; }
        public string ClientPassword { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
