//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishesView
    {
        public int DishID { get; set; }
        public string DishName { get; set; }
        public byte[] DishPhoto { get; set; }
        public string DishTypeName { get; set; }
        public string UnitOfMeasurementName { get; set; }
        public Nullable<decimal> PriceMeaning { get; set; }
        public string Composition { get; set; }
        public string IsEnough { get; set; }
        public Nullable<int> MaxCount { get; set; }
    }
}
