//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoOrderWhereID
    {
        public int ChequeID { get; set; }
        public string DishName { get; set; }
        public byte[] DishPhoto { get; set; }
        public Nullable<int> ProductCount { get; set; }
    }
}
