//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.InvoiceTabParts = new HashSet<InvoiceTabPart>();
            this.ReceiptTabParts = new HashSet<ReceiptTabPart>();
        }
    
        public int IngredientID { get; set; }
        public string IngredientName { get; set; }
        public Nullable<System.DateTime> IngredientExpirationDate { get; set; }
        public Nullable<int> IngredientCount { get; set; }
        public Nullable<int> UnitOfMeasurementID { get; set; }
    
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTabPart> InvoiceTabParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptTabPart> ReceiptTabParts { get; set; }
    }
}
