//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptTabPart
    {
        public int LineID { get; set; }
        public Nullable<int> IngredientCount { get; set; }
        public Nullable<int> ReceiptID { get; set; }
        public Nullable<int> IngredientID { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
