//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableInfo
    {
        public int ChequeID { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public int DishID { get; set; }
        public string DishName { get; set; }
        public Nullable<decimal> PriceMeaning { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string WorkerSurname { get; set; }
        public string WorkerName { get; set; }
        public string WorkerPatronymic { get; set; }
        public string WorkerPositionName { get; set; }
        public string ClientEmal { get; set; }
    }
}
