//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Cheques = new HashSet<Cheque>();
        }
    
        public int WorkerID { get; set; }
        public string WorkerSurname { get; set; }
        public string WorkerName { get; set; }
        public string WorkerPatronymic { get; set; }
        public Nullable<int> WorkerPositionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheques { get; set; }
        public virtual WorkerPosition WorkerPosition { get; set; }
        public virtual WorkerAuthorizationData WorkerAuthorizationData { get; set; }
    }
}
