//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerAuthorizationData
    {
        public int WorkerID { get; set; }
        public string WorkerLogin { get; set; }
        public string WorkerPassword { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
